[2024-12-07T03:39:44.509+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-07T03:39:44.541+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_listings_etl_v2.load_data manual__2024-12-07T03:39:29.729804+00:00 [queued]>
[2024-12-07T03:39:44.551+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_listings_etl_v2.load_data manual__2024-12-07T03:39:29.729804+00:00 [queued]>
[2024-12-07T03:39:44.552+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-12-07T03:39:44.566+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data> on 2024-12-07 03:39:29.729804+00:00
[2024-12-07T03:39:44.580+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T03:39:44.585+0000] {standard_task_runner.py:63} INFO - Started process 9179 to run task
[2024-12-07T03:39:44.586+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'job_listings_etl_v2', 'load_data', 'manual__2024-12-07T03:39:29.729804+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/ETL_FINAL_PROJECT (1).py', '--cfg-path', '/tmp/tmp4y4lkpu7']
[2024-12-07T03:39:44.591+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask load_data
[2024-12-07T03:39:44.676+0000] {task_command.py:426} INFO - Running <TaskInstance: job_listings_etl_v2.load_data manual__2024-12-07T03:39:29.729804+00:00 [running]> on host 1ed1f547130e
[2024-12-07T03:39:44.784+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='job_listings_etl_v2' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T03:39:29.729804+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T03:39:29.729804+00:00'
[2024-12-07T03:39:44.791+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-07T03:39:44.815+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-12-07T03:39:44.820+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-5.10.25-linuxkit-aarch64-with-glibc2.36
[2024-12-07T03:39:44.823+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-07T03:39:46.798+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-07T03:39:47.188+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-07T03:39:47.652+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-07T03:39:49.525+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-07T03:39:49.528+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-07T03:39:49.530+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-07T03:39:49.559+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=job_listings_etl_v2, task_id=load_data, run_id=manual__2024-12-07T03:39:29.729804+00:00, execution_date=20241207T033929, start_date=20241207T033944, end_date=20241207T033949
[2024-12-07T03:39:49.691+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-07T03:39:49.716+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T03:39:49.718+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
