[2024-12-03T07:01:13.163+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T07:01:13.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: job_listings_etl_v2.load_api manual__2024-12-03T07:00:48.695526+00:00 [queued]>
[2024-12-03T07:01:13.242+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: job_listings_etl_v2.load_api manual__2024-12-03T07:00:48.695526+00:00 [queued]>
[2024-12-03T07:01:13.249+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-12-03T07:01:13.271+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_api> on 2024-12-03 07:00:48.695526+00:00
[2024-12-03T07:01:13.290+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T07:01:13.298+0000] {standard_task_runner.py:63} INFO - Started process 671 to run task
[2024-12-03T07:01:13.299+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'job_listings_etl_v2', 'load_api', 'manual__2024-12-03T07:00:48.695526+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/ETL_FINAL_PROJECT (1).py', '--cfg-path', '/tmp/tmpvcbcwi9o']
[2024-12-03T07:01:13.308+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask load_api
[2024-12-03T07:01:13.399+0000] {task_command.py:426} INFO - Running <TaskInstance: job_listings_etl_v2.load_api manual__2024-12-03T07:00:48.695526+00:00 [running]> on host 2adeb2e19af7
[2024-12-03T07:01:13.553+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='job_listings_etl_v2' AIRFLOW_CTX_TASK_ID='load_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T07:00:48.695526+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T07:00:48.695526+00:00'
[2024-12-03T07:01:13.557+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T07:01:13.582+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-12-03T07:01:13.590+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-5.10.25-linuxkit-aarch64-with-glibc2.36
[2024-12-03T07:01:13.593+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-03T07:01:14.995+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-12-03T07:02:08.186+0000] {ETL_FINAL_PROJECT (1).py:132} INFO - Successfully loaded 50 records into Snowflake.
[2024-12-03T07:02:08.209+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-03T07:02:08.212+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T07:02:08.275+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=job_listings_etl_v2, task_id=load_api, run_id=manual__2024-12-03T07:00:48.695526+00:00, execution_date=20241203T070048, start_date=20241203T070113, end_date=20241203T070208
[2024-12-03T07:02:08.419+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-03T07:02:08.486+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T07:02:08.488+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
