[2024-12-05T17:25:34.752+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-05T17:25:34.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test scheduled__2024-12-04T07:00:00+00:00 [queued]>
[2024-12-05T17:25:34.811+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test scheduled__2024-12-04T07:00:00+00:00 [queued]>
[2024-12-05T17:25:34.812+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-12-05T17:25:34.838+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-12-04 07:00:00+00:00
[2024-12-05T17:25:34.860+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5322) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T17:25:34.867+0000] {standard_task_runner.py:63} INFO - Started process 5333 to run task
[2024-12-05T17:25:34.875+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'scheduled__2024-12-04T07:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmptp_4_fmw']
[2024-12-05T17:25:34.892+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask dbt_test
[2024-12-05T17:25:35.115+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test scheduled__2024-12-04T07:00:00+00:00 [running]> on host 2adeb2e19af7
[2024-12-05T17:25:35.537+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-04T07:00:00+00:00'
[2024-12-05T17:25:35.564+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-05T17:25:35.578+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-05T17:25:35.586+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/final_dbt --project-dir /opt/***/final_dbt']
[2024-12-05T17:25:35.661+0000] {subprocess.py:86} INFO - Output:
[2024-12-05T17:25:38.154+0000] {subprocess.py:93} INFO - [0m17:25:38  Running with dbt=1.8.7
[2024-12-05T17:25:39.071+0000] {subprocess.py:93} INFO - [0m17:25:39  Registered adapter: snowflake=1.8.4
[2024-12-05T17:25:39.318+0000] {subprocess.py:93} INFO - [0m17:25:39  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-12-05T17:25:39.320+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-12-05T17:25:39.326+0000] {subprocess.py:93} INFO - - models.final_dbt.example
[2024-12-05T17:25:39.559+0000] {subprocess.py:93} INFO - [0m17:25:39  Found 2 snapshots, 3 models, 2 sources, 459 macros
[2024-12-05T17:25:39.568+0000] {subprocess.py:93} INFO - [0m17:25:39
[2024-12-05T17:25:39.571+0000] {subprocess.py:93} INFO - [0m17:25:39  Nothing to do. Try checking your model configs and model specification args
[2024-12-05T17:25:41.242+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-05T17:25:41.258+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-05T17:25:41.406+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=scheduled__2024-12-04T07:00:00+00:00, execution_date=20241204T070000, start_date=20241205T172534, end_date=20241205T172541
[2024-12-05T17:25:41.483+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-05T17:25:41.603+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-05T17:25:41.606+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
