[2024-12-05T17:24:54.225+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-05T17:24:54.245+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-05T17:24:34.656886+00:00 [queued]>
[2024-12-05T17:24:54.251+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-05T17:24:34.656886+00:00 [queued]>
[2024-12-05T17:24:54.256+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-05T17:24:54.265+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-12-05 17:24:34.656886+00:00
[2024-12-05T17:24:54.276+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5273) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T17:24:54.278+0000] {standard_task_runner.py:63} INFO - Started process 5275 to run task
[2024-12-05T17:24:54.277+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-12-05T17:24:34.656886+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp2h5_zn3_']
[2024-12-05T17:24:54.284+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask dbt_test
[2024-12-05T17:24:54.316+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-05T17:24:34.656886+00:00 [running]> on host 2adeb2e19af7
[2024-12-05T17:24:54.408+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T17:24:34.656886+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T17:24:34.656886+00:00'
[2024-12-05T17:24:54.411+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-05T17:24:54.413+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-05T17:24:54.414+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/final_dbt --project-dir /opt/***/final_dbt']
[2024-12-05T17:24:54.430+0000] {subprocess.py:86} INFO - Output:
[2024-12-05T17:24:56.582+0000] {subprocess.py:93} INFO - [0m17:24:56  Running with dbt=1.8.7
[2024-12-05T17:24:58.309+0000] {subprocess.py:93} INFO - [0m17:24:58  Registered adapter: snowflake=1.8.4
[2024-12-05T17:24:58.968+0000] {subprocess.py:93} INFO - [0m17:24:58  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-12-05T17:24:58.976+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-12-05T17:24:58.977+0000] {subprocess.py:93} INFO - - models.final_dbt.example
[2024-12-05T17:24:59.159+0000] {subprocess.py:93} INFO - [0m17:24:59  Found 2 snapshots, 3 models, 2 sources, 459 macros
[2024-12-05T17:24:59.165+0000] {subprocess.py:93} INFO - [0m17:24:59
[2024-12-05T17:24:59.169+0000] {subprocess.py:93} INFO - [0m17:24:59  Nothing to do. Try checking your model configs and model specification args
[2024-12-05T17:25:00.449+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-05T17:25:00.472+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-05T17:25:00.565+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-12-05T17:24:34.656886+00:00, execution_date=20241205T172434, start_date=20241205T172454, end_date=20241205T172500
[2024-12-05T17:25:00.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-05T17:25:00.713+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-05T17:25:00.717+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
