[2024-12-05T17:23:46.008+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-05T17:23:46.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-05T17:23:22.357976+00:00 [queued]>
[2024-12-05T17:23:46.027+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-05T17:23:22.357976+00:00 [queued]>
[2024-12-05T17:23:46.028+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-05T17:23:46.035+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-12-05 17:23:22.357976+00:00
[2024-12-05T17:23:46.048+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T17:23:46.052+0000] {standard_task_runner.py:63} INFO - Started process 5215 to run task
[2024-12-05T17:23:46.050+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-12-05T17:23:22.357976+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpbdcfd7l1']
[2024-12-05T17:23:46.056+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask dbt_test
[2024-12-05T17:23:46.094+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-12-05T17:23:22.357976+00:00 [running]> on host 2adeb2e19af7
[2024-12-05T17:23:46.155+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T17:23:22.357976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T17:23:22.357976+00:00'
[2024-12-05T17:23:46.157+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-05T17:23:46.158+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-05T17:23:46.159+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/final_dbt --project-dir /opt/***/final_dbt']
[2024-12-05T17:23:46.176+0000] {subprocess.py:86} INFO - Output:
[2024-12-05T17:23:47.710+0000] {subprocess.py:93} INFO - [0m17:23:47  Running with dbt=1.8.7
[2024-12-05T17:23:48.386+0000] {subprocess.py:93} INFO - [0m17:23:48  Registered adapter: snowflake=1.8.4
[2024-12-05T17:23:48.588+0000] {subprocess.py:93} INFO - [0m17:23:48  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-12-05T17:23:48.589+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-12-05T17:23:48.590+0000] {subprocess.py:93} INFO - - models.final_dbt.example
[2024-12-05T17:23:48.745+0000] {subprocess.py:93} INFO - [0m17:23:48  Found 2 snapshots, 3 models, 2 sources, 459 macros
[2024-12-05T17:23:48.749+0000] {subprocess.py:93} INFO - [0m17:23:48
[2024-12-05T17:23:48.751+0000] {subprocess.py:93} INFO - [0m17:23:48  Nothing to do. Try checking your model configs and model specification args
[2024-12-05T17:23:49.565+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-05T17:23:49.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-05T17:23:49.617+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-12-05T17:23:22.357976+00:00, execution_date=20241205T172322, start_date=20241205T172346, end_date=20241205T172349
[2024-12-05T17:23:49.690+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-05T17:23:49.738+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-05T17:23:49.740+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
